#!/usr/bin/env php

<?php

require __DIR__.'/vendor/autoload.php';

use App\Command\ReadDataCommand;
use App\Command\WriteDataCommand;
use Symfony\Component\Console\Application;


$app = new Application();

$app->add(new ReadDataCommand());
$app->add(new WriteDataCommand());

// $app->setDefaultCommand($command->getName(), true);

$app->run();
?>